<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body>
<script>
// promise retry
// 实现思路：通过try catch 来捕捉promise的reject,通过 ！times 来判断是否达到重试次数，如果达到则返回错误。
Promise.retry = function (promiseFn, times = 3) {
  return new Promise(async (resolve, reject) => {
    while (times--) {
      try {
        // 循环调用需要重试的函数，直到达到指定的重试次数
        var ret = await promiseFn();
        //成功
        console.log(ret)
        resolve(ret);
        break;
      } catch (error) {
        console.log('error',error)
        // 达到重试次数，仍没有成功则返回错误信息
        if (!times) reject(error);
      }
    }
  });
}
function getProm() {
  const n = Math.random().toFixed(2);
  return new Promise((resolve, reject) => {
    setTimeout(() =>  n > 0.9 ? resolve('成功了'+n) : reject('失败了'+n), 100);
  });
}
Promise.retry(getProm,10);
</script>
</body>
</html>
